#!/bin/sh


# USE ANACONDA
# shell will use anaconda python interpreter instead of system python if it set to 1
USE_ANACONDA=0

# USE CONDA
# enable conda package manager if it set to 1
USE_CONDA=1


# CONDA ENV
CONDA_ENV=base

# Enable Matlab
USE_MATLAB=1

# Enable JFX Library
USE_JFX=1

# Enable BCC toolset
USE_BCCTOOL=1

# Enable some helpful ev for gentoo
USE_GENTOO=1
