#!/bin/sh


# USE ANACONDA
# shell will use anaconda python interpreter instead of system python if it set to 1
USE_ANACONDA=1

# USE CONDA
# enable conda package manager if it set to 1
USE_CONDA=1

# CONDA ENV
CONDA_ENV=base

# Enable Matlab
USE_MATLAB=1

# Enable JFX Library
USE_JFX=1

# Enable BCC toolset
USE_BCCTOOL=1

# Enable some helpful ev for gentoo
USE_GENTOO=1

# USE EDITOR
USE_EDITOR=micro

# Enable local gem library
USE_USERGEMHOME=1

# Enable risc-v 64 toolchain
USE_RV64TOOLCHAIN=1

# Enable local Qt lib
USE_LOCALQT=1

# Enable local rust library
USE_LOCALRUSTLIB=1

# Enable local Musl C library
USE_LOCALMUSL=1

# Enable Android CLI toolset
USE_ANDROID_CLI_TOOLSET=1

# Enable local flutter
USE_FLUTTER=1

# Enable dotnet
USE_DOTNET=1

# Enable local openssl3 library
USE_LOCAL_OPENSSL3=0

# LLVM Support
USE_LLVM=1
LLVM_TOOLCHAIN_VER=14
