#!/bin/sh

# USE ANACONDA
# shell will use anaconda python interpreter instead of system python if it set to 1
USE_ANACONDA=1

# USE CONDA
# enable conda package manager if it set to 1
USE_CONDA=1

# CONDA ENV
CONDA_ENV=py310

# Enable Matlab
USE_MATLAB=1

# Enable JFX Library
USE_JFX=1

# Enable BCC toolset
USE_BCCTOOL=1

# Enable some helpful ev for gentoo
USE_GENTOO=1

# USE EDITOR
USE_EDITOR=micro

# Specified local ruby version
RUBY_VERSION=3.1.0

# Enable local gem library
USE_USERGEMHOME=1

# Enable risc-v 64 toolchain
USE_RV64TOOLCHAIN=0

# Enable local Qt lib
USE_LOCALQT=1

# Enable local rust library
USE_LOCALRUSTLIB=1

# Enable local Musl C library
USE_LOCALMUSL=1

# Enable Android CLI toolset
USE_ANDROID_CLI_TOOLSET=1

# specify Android SDK Version
USE_ANRDOID_BUILD_TOOLS_VERSION=33.0.0

# specify Android NDK Version
USE_NDK_VERSION=25.1.8937393

# Enable local flutter
USE_FLUTTER=1

# Enable dotnet
USE_DOTNET=1

# Enable local openssl3 library
USE_LOCAL_OPENSSL3=0

# LLVM Support
USE_SYS_LLVM_TOOLCHAIN=1
SYS_LLVM_TOOLCHAIN_VER=14

# Enable local ICU Library (Version 69.1)
USE_LOCAL_ICU=1

# repoupdate command max re-try times.
REPOUPDATE_RETRY_MAX=10

# When the quantity of packages that can be upgraded is greater 
# than or equal to this value, repoupdate will suggest a system upgrade.
# Values: [NUM/"AUTO"]
REPOUPDATE_SUGGESTED_UPGRADABLE_QUANTITY=AUTO

# The packages specified here are always automatically upgraded via repoupdate
# when eix detected updates of them, regardless of whether the quantity of upgradable 
# softwares reach the suggest value defined above.
REPOUPDATE_ALWAYS_UPDATE=(
	"sys-kernel/xanmod-sources"
	"sys-kernel/linux-firmware"
	"sys-apps/portage"
	"sys-apps/openrc"
	"sys-devel/binutils"
	"sys-devel/binutils-config"
	"sys-libs/binutils-libs"
	"sys-libs/glibc"
)

# check git status at shell startup.
CHECK_GIT_STATUS_ON_STARTUP=(
	$HOME/.env
);

# enable local intel icx compilers
USE_LOCAL_ICX_COMPILERS=1

# specify local icx compilers version (default: latest)
LOCAL_ICX_COMPILERS_VERSION=latest

# enable local intel tbb library
USE_LOCAL_TBB=1

# specify local intel tbb library version (default: latest)
LOCAL_TBB_VERSION=latest

# enable local intel openAPI clang compiler
USE_LOCAL_ICX_CLANG=1

# enable local intel MPI library.
USE_LOCAL_INTEL_MPI_LIB=1
