#!/bin/sh

# but do not excute it!

if [[ ${UID} -ne 1000 ]]
then
	echo "Incorret UID ${UID}!!!"
	echo "Attempting env source!"
	return 133
fi

source $HOME/.env/env_preset
source $HOME/.env/functions/.func_dir_init
source $HOME/.env/evars/.evars_init
source $HOME/.env/alias

#git status --porcelain $HOME/.env/

for i in ${STARTUP_GIT_STATUS_CHECK_DIRS}; do
	git status --porcelain ${i}
done