#!/bin/sh

# but do not excute it!

if [[ ${UID} -ne 1000 ]]
then
	echo "Incorret UID ${UID}!!!"
	echo "Environment loading process attempted!"
	return 133
fi

source $HOME/.env/env_preset
source $HOME/.env/functions/.func_dir_init
source $HOME/.env/evars/.evars_init
source $HOME/.env/alias

for i in ${CHECK_GIT_STATUS_ON_STARTUP}; do
	pushd ${i} &>/dev/null
	git status --porcelain 
	popd &>/dev/null
done

# reload environment.
alias env_reload="source $HOME/.shrc"
